//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination
    {
        public string ClientID { get; set; }
        public int NumberVaccination { get; set; }
        public System.DateTime DateVaccination { get; set; }
        public string VaccineManufacturer { get; set; }
        public int ID { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
